### PR TITLE
Resolve static content at STATIC_ROOT

### PR DESCRIPTION
**Pull request by jarshwah**
Server Render doesn't resolve hashed static content at STATIC_ROOT - this changes that.

The tests are pretty badly broken by the way, should probably get it onto circle or gh. I couldn't get them running on my local properly.

### CODE REVIEW

**Comment by mic159** [comment]
Travis is running, its just not showing as checks.

https://travis-ci.org/github/mic159/react-render/builds/686563365

**Comment by jarshwah** [comment]
Ahh - any idea why "React" is showing as invalid token?

**Comment by mic159** [comment]
It's because you changed test_functionality from using the webpack-compiled javascript to trying to directly use JSX files.

**Comment by mic159** [comment]
Fixed in #28

**Pull request closed without merging**
